<?php

function custom_addhands_menu(){
  $items = array();

  $items['main'] = array(
    'page callback' => 'custom_addhands_frontpage_callback',
    'access callback' => true,
    'title' => '',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function custom_addhands_frontpage_callback(){
  drupal_set_title('');
  drupal_add_js(drupal_get_path('module', 'custom_addhands') . '/addhands.js');
  return '';
}

/*
 * Implimentation hook_block_info()
 */
function custom_addhands_block_info(){
  $block['footer_logo']['info'] = t('Footer Logo');
  $block['footer_contacts']['info'] = t('Footer Contacts');

  return $block;
}

/*
* Implimentation hook_block_view()
*/

function custom_addhands_block_view($delta){
  $output='';

  switch($delta){
    case 'footer_logo':
      $output = '<div class="f-logo-wrapper">' . theme('image', array('path' => theme_get_setting('ilogo'), 'attributes' => array('class'=>'f-logo'))) . '</div>';
      $output .= '<div class="f-copy-wrapper">&copy;&nbsp' . date('Y') . '</div>';
      break;
  }
  $block['content'] = $output;
  return $block;
}
