<?php

require_once 'geofield_ymap.element.inc';
require_once 'geofield_ymap.widget.inc';
require_once 'geofield_ymap.formatter.inc';
require_once 'geofield_ymap.filter.inc';

/**
 * Implements hook_menu().
 */
function geofield_ymap_menu() {
  $items = array();

  $items['admin/config/system/geofield-ymap'] = array(
    'title' => 'Geofield Yandex Maps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geofield_ymap_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'geofield_ymap.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function geofield_ymap_init() {
  if (variable_get('geofield_ymap_use_loader', FALSE)) {
    $module_path = drupal_get_path('module', 'geofield_ymap');
    drupal_add_js(array(
      'geofieldYmap' => array(
        'modulePath' => base_path() . $module_path,
        'presetsPath' => variable_get('geofield_ymap_presets_path', ''),
        'preset' => variable_get('geofield_ymap_preset', ''),
      ),
    ), 'setting');
    drupal_add_js($module_path . '/js/geofield_ymap_loader.js');
  }
}

/**
 * Implements hook_library().
 */
function geofield_ymap_library() {
  $module_path = drupal_get_path('module', 'geofield_ymap');
  $settings = array(
    'geofieldYmap' => array(
      'modulePath' => base_path() . $module_path,
      'preset' => variable_get('geofield_ymap_preset', ''),
    ),
  );
  $library = array(
    'geofield_ymap' => array(
      'title' => 'Geofield Yandex Maps',
      'version' => '1',
      'js' => array(
        array('data' => $settings, 'type' => 'setting'),
        array('data' => '//api-maps.yandex.ru/2.1-dev/?lang=ru-RU&load=package.full&coordorder=longlat', 'type' => 'external'),
        array('data' => $module_path . '/js/geofield_ymap.js'),
      ),
      'css' => array(
        array('data' => $module_path . '/geofield_ymap.css'),
      ),
    ),
  );
  if ($presets_path = variable_get('geofield_ymap_presets_path', '')) {
    $library['geofield_ymap']['js'][] = array('data' => $presets_path);
  }
  return $library;
}

/**
 * Implements hook_theme().
 */
function geofield_ymap_theme() {
  return array(
    'geofield_ymap' => array(
      'render element' => 'element',
      'file' => 'geofield_ymap.theme.inc',
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function geofield_ymap_views_api() {
  return array('api' => 3);
}

/**
 * Convert field items to GeoJSON.
 */
function geofield_ymap_items_to_geojson($items) {
  if (!$items) {
    return '';
  }

  geophp_load();

  $result = array();
  foreach ($items as $delte => $item) {
    if (!empty($item['geom'])) {
      $geoms = geoPHP::load($item['geom']);
      foreach (geofield_ymap_split_objects($geoms) as $geom) {
        $result[] = $geom->out('json', TRUE);
      }
    }
  }

  return $result ? $result : '';
}

/**
 * Split MultiType object to separate objects.
 */
function geofield_ymap_split_objects($geom) {
  $geoms = array();
  if (in_array($geom->geometryType(), array('GeometryCollection', 'MultiPoint', 'MultiLineString', 'MultiPolygon'))) {
    foreach ($geom->getComponents() as $component) {
      $geoms = array_merge($geoms, geofield_ymap_split_objects($component));
    }
  }
  else {
    $geoms = array($geom);
  }
  return $geoms;
}

/**
 * Return map types.
 */
function _geofield_ymap_get_map_types() {
  return array(
    'yandex#map'             => t('Roadmap'),
    'yandex#satellite'       => t('Satelite'),
    'yandex#hybrid'          => t('Hybrid'),
    'yandex#publicMap'       => t('Public map'),
    'yandex#publicMapHybrid' => t('Hybrid public map'),
  );
}

/**
 * Return json encoded array.
 */
function _geofield_ymap_json_encode($array) {
  if (defined('JSON_UNESCAPED_UNICODE')) {
    return json_encode($array, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
  }
  return json_encode($array);
}
